"""added

Revision ID: 03001d60be86
Revises: 040ef953136b
Create Date: 2026-03-16 17:11:11.715492

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '03001d60be86'
down_revision = '040ef953136b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_internal_user', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_internal_user')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
