"""added

Revision ID: 040ef953136b
Revises: b0401d2a1735
Create Date: 2026-03-16 14:52:32.318479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040ef953136b'
down_revision = 'b0401d2a1735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('project_pkey'))
    )
    # ### end Alembic commands ###
