"""m,igrate

Revision ID: b0401d2a1735
Revises: fc7fdb9ad0cc
Create Date: 2026-03-15 16:52:57.768115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0401d2a1735'
down_revision = 'fc7fdb9ad0cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_sheet')
    op.drop_table('project_project')
    op.drop_table('task')
    op.drop_table('project_task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_task',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('project_task_pkey'))
    )
    op.create_table('task',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('initiated', 'completed', 'cancelled', name='taskstatus'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['project_task.id'], name=op.f('task_task_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('task_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('task_pkey'))
    )
    op.create_table('project_project',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('project_project_project_id_fkey')),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name=op.f('project_project_task_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('project_project_pkey'))
    )
    op.create_table('project',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('project_pkey'))
    )
    op.create_table('time_sheet',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('from_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('to_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('initiated', 'completed', 'cancelled', name='taskstatus'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project_project.id'], name=op.f('time_sheet_project_id_fkey')),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name=op.f('time_sheet_task_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('time_sheet_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('time_sheet_pkey'))
    )
    # ### end Alembic commands ###
