"""upgrade models

Revision ID: fc7fdb9ad0cc
Revises: e693aa365bfe
Create Date: 2026-03-15 14:51:18.231784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc7fdb9ad0cc'
down_revision = 'e693aa365bfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('project_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('project_task_id_fkey'), type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('task_id')

    with op.batch_alter_table('project_task', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('project_task_user_id_fkey'), type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('status')

    with op.batch_alter_table('time_sheet', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('time_sheet_task_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('time_sheet_project_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'task', ['task_id'], ['id'])
        batch_op.create_foreign_key(None, 'project_project', ['project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_sheet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('time_sheet_project_id_fkey'), 'project', ['project_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('time_sheet_task_id_fkey'), 'project_task', ['task_id'], ['id'])

    with op.batch_alter_table('project_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', postgresql.ENUM('initiated', 'completed', 'cancelled', name='taskstatus'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('project_task_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('project_task_id_fkey'), 'project_task', ['task_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('project_user_id_fkey'), 'users', ['user_id'], ['id'])

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('email', name=op.f('user_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('user_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
